---
- name: Reconcile docker application compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker_application_compose_dir }}"
    files: "{{ docker_application_compose_files }}"
    env_files: "{{ docker_application_env_files | default(omit) }}"
    state: present
    pull: "{{ docker_application_pull_policy }}"
    remove_orphans: "{{ docker_application_remove_orphans }}"
  register: docker_application_reconcile_result
  until: docker_application_reconcile_result is succeeded
  retries: "{{ docker_application_compose_retries }}"
  delay: "{{ docker_application_compose_retry_delay }}"

- name: Restart docker application
  community.docker.docker_compose_v2:
    project_src: "{{ docker_application_compose_dir }}"
    files: "{{ docker_application_compose_files }}"
    env_files: "{{ docker_application_env_files | default(omit) }}"
    state: restarted
